### ISSUE TITLE
requestBuilds parameters are incorrect for snap builds

### ISSUE THREAD

**Issue by cjwatson** [canonical-web-and-design/canonicalwebteam.launchpad#13]
Re-filing https://bugs.launchpad.net/launchpad/+bug/1867689 here.

`Launchpad.build_snap` passes incorrect parameters to Launchpad's `snap.requestBuilds` method.  Here's the location of the incorrect code:

  https://github.com/canonical-web-and-design/canonicalwebteam.launchpad/blob/master/canonicalwebteam/launchpad/models.py#L237-L244

The old code in build.snapcraft.io was correct, and looked like this instead:

  https://github.com/canonical-web-and-design/build.snapcraft.io/blob/master/src/server/handlers/launchpad.js#L842-L848

canonicalwebteam.launchpad's logic should be replaced with the correct logic from build.snapcraft.io: it should copy `auto_build_archive` and `auto_build_pocket` from the snap to the `archive` and `pocket` parameters respectively, and if the snap has a non-null `auto_build_channels` property then it should pass that as the `channels` parameter.  It should *not* pass `"channels": "snapcraft,apt"`.

I'm happy to consult on anything else where you aren't sure what the correct parameters are - I wrote most of the relevant code in build.snapcraft.io and still help to maintain the Launchpad end of things.

**Comment by sergiusens** [comment]
This should be fixed rather urgently, many are building with the wrong snapcaft.

**Comment by nottrobin** [comment]
Originally introduced here: https://github.com/canonical-web-and-design/snapcraft.io/commit/b0b18c9c22c95dcedcb208df33afbcd8cfa2d19d
