### ISSUE TITLE
Extract launchpad hostname so that we can use staging API's too

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/canonicalwebteam.launchpad#30]
See https://github.com/canonical-web-and-design/snapcraft.io/issues/2845 for context

**Comment by anthonydillon** [comment]
@tbille is this needed anymore?

**Comment by jkfran** [comment]
It would be nice to do it, however, it is not needed for Snapcraft as we have a staging user under the production API.

I would prefer to leave it open, I will take care.
